const money=n=>Number(n||0).toLocaleString('vi-VN')+'đ';
const normalizeMedia=src=>{if(!src)return'placeholder.svg';let s=String(src).trim().replace(/\\/g,'/');if(!s)return'placeholder.svg';if(/^(https?:|data:|blob:)/i.test(s))return s;if(s.startsWith('./'))s=s.slice(2);if(s==='placeholder.svg'||s.endsWith('/placeholder.svg'))return'placeholder.svg';if(s.startsWith('/'))s=s.slice(1);if(s.startsWith('media/'))return s;return'media/'+s;};
const getImages=p=>{let a=[];if(Array.isArray(p.images))a=p.images;else if(typeof p.images==='string'&&p.images.trim())a=[p.images];else if(p.image)a=[p.image];a=a.filter(Boolean).map(normalizeMedia);return a.length?a:['placeholder.svg'];};
const sources=[['products-camera.json','Camera'],['products-computer.json','Máy tính'],['products-printer.json','Máy in'],['products-network.json','Thiết bị mạng']];
async function loadProducts(){const groups=await Promise.all(sources.map(async([file,category])=>{try{const r=await fetch(file,{cache:'no-store'});if(!r.ok)return[];const list=await r.json();return Array.isArray(list)?list.map(p=>({...p,category:p.category||category})):[];}catch{return[];}}));return groups.flat();}
function productCard(p){const href=`product.html?id=${encodeURIComponent(p.id)}`, image=getImages(p)[0];const el=document.createElement('article');el.className='product-card compact';el.innerHTML=`<a class="product-image" href="${href}"><img loading="lazy" decoding="async" src="${image}" alt="${p.name}"></a><div class="product-body"><h3><a class="product-name-link" href="${href}">${p.name}</a></h3><div class="price">${money(p.price)}${p.old_price?`<span class="old-price">${money(p.old_price)}</span>`:''}</div></div>`;const img=el.querySelector('img');img.addEventListener('error',()=>{img.src='placeholder.svg';},{once:true});return el;}
function renderProducts(grid,list,empty){grid.innerHTML='';if(empty)empty.hidden=list.length!==0;list.forEach(p=>grid.appendChild(productCard(p)));}
async function loadHome(){const grid=document.querySelector('#featuredProductGrid');if(grid){const products=await loadProducts();const featured=products.filter(p=>p.featured===true).slice(0,6);renderProducts(grid,featured,document.querySelector('#featuredEmpty'));}
const pgrid=document.querySelector('#homeProjectGrid');if(pgrid)loadProjects(pgrid,document.querySelector('#homeProjectEmpty'),true,3);}
async function loadProductsPage(){const grid=document.querySelector('#productGrid');if(!grid)return;const products=await loadProducts();const search=document.querySelector('#search'), select=document.querySelector('#category'), title=document.querySelector('#productsTitle'), empty=document.querySelector('#empty');const urlCategory=new URLSearchParams(location.search).get('category')||'';if(select&&urlCategory)select.value=urlCategory;
const apply=()=>{const q=(search?.value||'').toLowerCase().trim(),c=select?.value||'';const list=products.filter(p=>(!c||p.category===c)&&(!q||(p.name+' '+(p.brand||'')+' '+(p.description||'')).toLowerCase().includes(q)));if(title)title.textContent=c?`Sản phẩm ${c}`:'Tất cả sản phẩm';renderProducts(grid,list,empty);};search?.addEventListener('input',apply);select?.addEventListener('change',()=>{const c=select.value;history.replaceState(null,'',c?`products.html?category=${encodeURIComponent(c)}`:'products.html');apply();});apply();}
async function loadProjects(grid,empty,featuredOnly=false,limit=999){try{const r=await fetch('projects.json',{cache:'no-store'}),list=await r.json();let items=Array.isArray(list)?list:[];if(featuredOnly)items=items.filter(p=>p.featured===true);items=items.slice(0,limit);grid.innerHTML='';if(empty)empty.hidden=items.length!==0;items.forEach(p=>{const image=getImages(p)[0];const el=document.createElement('article');el.className='project-card';el.innerHTML=`<a class="project-image" href="project.html?id=${encodeURIComponent(p.id)}"><img loading="lazy" decoding="async" src="${image}" alt="${p.title}"></a><div class="project-body"><span class="badge">${p.project_type||'Công trình'}</span><h3>${p.title}</h3><div class="muted">${p.location||''}${p.completed?' • '+p.completed:''}</div><p>${String(p.description||'').slice(0,130)}${String(p.description||'').length>130?'…':''}</p><a class="project-view" href="project.html?id=${encodeURIComponent(p.id)}">Xem công trình →</a></div>`;el.querySelector('img').addEventListener('error',e=>e.currentTarget.src='placeholder.svg',{once:true});grid.appendChild(el);});}catch(e){console.error(e);if(empty)empty.hidden=false;}}
async function loadProjectsPage(){const grid=document.querySelector('#projectGrid');if(grid)loadProjects(grid,document.querySelector('#projectEmpty'),false,999);}
document.addEventListener('DOMContentLoaded',()=>{loadHome();loadProductsPage();loadProjectsPage();});
