let products=[];
const money=n=>Number(n||0).toLocaleString('vi-VN')+'đ';
const normalizeMedia=src=>{if(!src)return'placeholder.svg';let s=String(src).trim().replace(/\\/g,'/');if(!s)return'placeholder.svg';if(/^(https?:|data:|blob:)/i.test(s))return s;if(s.startsWith('./'))s=s.slice(2);if(s==='placeholder.svg'||s.endsWith('/placeholder.svg'))return'placeholder.svg';if(s.startsWith('/'))return s;if(s.startsWith('media/'))return s;return 'media/'+s;};
const getImages=p=>{let a=[];if(Array.isArray(p.images))a=p.images;else if(typeof p.images==='string'&&p.images.trim())a=[p.images];else if(p.image)a=[p.image];a=a.filter(Boolean).map(normalizeMedia);return a.length?a:['placeholder.svg'];};
const sources=[['products-camera.json','Camera'],['products-computer.json','Máy tính'],['products-printer.json','Máy in'],['products-network.json','Thiết bị mạng']];
async function load(){try{const groups=await Promise.all(sources.map(async([file,category])=>{const r=await fetch(file,{cache:'no-store'});if(!r.ok)return[];const list=await r.json();return Array.isArray(list)?list.map(p=>({...p,category:p.category||category})):[];}));products=groups.flat();renderFeatured();loadProjects();}catch(e){console.error(e);document.querySelector('#empty').hidden=false;loadProjects();}}
function render(list){const grid=document.querySelector('#productGrid');grid.innerHTML='';document.querySelector('#empty').hidden=list.length!==0;list.forEach(p=>{const image=getImages(p)[0];const href=`product.html?id=${encodeURIComponent(p.id)}`;const el=document.createElement('article');el.className='product-card compact';el.innerHTML=`<a class="product-image" href="${href}"><img loading="lazy" decoding="async" src="${image}" alt="${p.name}"></a><div class="product-body"><h3><a class="product-name-link" href="${href}">${p.name}</a></h3><div class="price">${money(p.price)}${p.old_price?`<span class="old-price">${money(p.old_price)}</span>`:''}</div></div>`;const img=el.querySelector('img');img.addEventListener('error',()=>{if(!img.src.endsWith('placeholder.svg'))img.src='placeholder.svg';},{once:true});grid.appendChild(el);});}
async function loadProjects(){const grid=document.querySelector('#projectGrid'),empty=document.querySelector('#projectEmpty');if(!grid)return;try{const r=await fetch('projects.json',{cache:'no-store'}),list=await r.json();const items=(Array.isArray(list)?list:[]).filter(p=>p.featured!==false);grid.innerHTML='';empty.hidden=items.length!==0;items.slice(0,8).forEach(p=>{const image=getImages(p)[0];const el=document.createElement('article');el.className='project-card';el.innerHTML=`<a class="project-image" href="project.html?id=${encodeURIComponent(p.id)}"><img loading="lazy" decoding="async" src="${image}" alt="${p.title}"></a><div class="project-body"><span class="badge">${p.project_type||'Công trình'}</span><h3>${p.title}</h3><div class="muted">${p.location||''}${p.completed?' • '+p.completed:''}</div><p>${String(p.description||'').slice(0,130)}${String(p.description||'').length>130?'…':''}</p><a class="view project-view" href="project.html?id=${encodeURIComponent(p.id)}">Xem công trình</a></div>`;const img=el.querySelector('img');img.addEventListener('error',()=>img.src='placeholder.svg',{once:true});grid.appendChild(el);});}catch(e){console.error(e);empty.hidden=false;}}
function setProductsTitle(text){const h=document.querySelector('#products .showcase-title h2');if(h)h.textContent=text;}
function renderFeatured(){const featured=products.filter(p=>p.featured!==false);setProductsTitle('Sản phẩm nổi bật');render(featured);}
function apply({scroll=false}={}){const search=document.querySelector('#search'),select=document.querySelector('#category');const q=(search?.value||'').toLowerCase().trim();const c=select?.value||'';if(!q&&!c){renderFeatured();}else{const filtered=products.filter(p=>(!c||p.category===c)&&(!q||(p.name+' '+(p.brand||'')+' '+(p.description||'')).toLowerCase().includes(q)));setProductsTitle(c?`Sản phẩm ${c}`:'Kết quả tìm kiếm');render(filtered);}if(scroll){requestAnimationFrame(()=>document.querySelector('#products')?.scrollIntoView({behavior:'smooth',block:'start'}));}}
document.querySelector('#search')?.addEventListener('input',()=>apply());document.querySelector('#category')?.addEventListener('change',()=>apply());document.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{const select=document.querySelector('#category');if(select)select.value=b.dataset.cat;const search=document.querySelector('#search');if(search)search.value='';apply({scroll:true});}));const mobileLinks=document.querySelector('.links');
function openMobileMenu(){if(!mobileLinks)return;mobileLinks.style.display='flex';mobileLinks.style.position='absolute';mobileLinks.style.top='74px';mobileLinks.style.left='4%';mobileLinks.style.right='4%';mobileLinks.style.flexDirection='column';mobileLinks.style.background='#fff';mobileLinks.style.padding='12px';mobileLinks.style.borderRadius='12px';mobileLinks.style.boxShadow='0 15px 40px rgba(0,0,0,.12)';}
function closeMobileMenu(){if(!mobileLinks)return;mobileLinks.style.display='none';}
document.querySelector('.menu-btn')?.addEventListener('click',()=>{if(!mobileLinks)return;mobileLinks.style.display==='flex'?closeMobileMenu():openMobileMenu();});
document.querySelectorAll('.links a').forEach(a=>a.addEventListener('click',()=>{if(window.matchMedia('(max-width:900px)').matches)closeMobileMenu();}));
window.addEventListener('resize',()=>{if(window.innerWidth>900&&mobileLinks){mobileLinks.removeAttribute('style');}});
load();
